// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhwiwovoasjoirgwetke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVod2l3b3ZvYXNqb2lyZ3dldGtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MzU3NjQsImV4cCI6MjA2NTMxMTc2NH0.XQpFcHYAmn5rqe--ZWaXhsw5kExlpWCiWGLEAlOMmqI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);